name: livelinesstemplate
version: 1.0.0+1
publish_to: none
description: A template for Liveliness frontend development
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.3.1
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  flutter_svg: ^1.0.3
  google_fonts: ^4.0.4
  flag: ^5.0.1
  intl: ^0.18.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/animation/
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/
  uses-material-design: true
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/Urbanist-VariableFont_wght.ttf
        - asset: assets/Urbanist-ExtraBold.ttf
          weight: 900
